name: golangci-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Create coverage directory
              run: mkdir -p coverage

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: 1.25.1

            - name: Install dependencies
              run: |
                go get -v -t -d ./...
                go mod vendor
                go mod tidy

            - name: Run tests
              run: |
                go test -race ./... -count=1 -p 1 -covermode=atomic -coverprofile=coverage/coverage.out
